print: True
save: True
save_path: ${output_dir}/config_tree.log
style: dim
guide_style: dim
fields_order: 
  - cl_algorithm
  - cl_dataset
  - backbone
  - optimizer
  - lr_scheduler
  - trainer
  - callbacks
  - lightning_loggers
  - hydra
  - misc
