# configs for Hydra
# https://hydra.cc/docs/configure_hydra/intro/

# Hydra is automatically configured with defaults. These are overrides.

# enable hydra-colorlog
defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

job_logging:
  root:
    level: INFO # set pylogger level
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/console.log

run:
  dir: ${output_dir}

