_target_: clarena.cl_datasets.Combined
validation_percentage: 0.1
test_percentage: 0.1
batch_size: 128
datasets: 
  - torchvision.datasets.CIFAR10
  - torchvision.datasets.CIFAR100
  - torchvision.datasets.MNIST
  - torchvision.datasets.SVHN
  - torchvision.datasets.FashionMNIST
  - torchvision.datasets.GTSRB
  - clarena.cl_datasets.original.FaceScrub100
  - clarena.cl_datasets.original.NotMNIST
  - clarena.cl_datasets.original.EMNISTDigits
  - clarena.cl_datasets.original.EMNISTLetters
  - clarena.cl_datasets.original.ArabicHandwrittenDigits
  - clarena.cl_datasets.original.KannadaMNIST
  - clarena.cl_datasets.original.SignLanguageMNIST
  - torchvision.datasets.KMNIST
  - torchvision.datasets.Food101
  - clarena.cl_datasets.original.Linnaeus5_32
  - torchvision.datasets.Caltech101
  - torchvision.datasets.EuroSAT
  - torchvision.datasets.DTD
  - torchvision.datasets.Country211
root: 
  - data/CIFAR10
  - data/CIFAR100
  - data/MNIST
  - data/SVHN
  - data/FashionMNIST
  - data/GTSRB
  - data/FaceScrub
  - data/NotMNIST
  - data/EMNIST
  - data/EMNIST
  - data/AHDD
  - data/KannadaMNIST
  - data/SignLanguageMNIST
  - data/KMNIST
  - data/Food101
  - data/Linnaeus5
  - data/Caltech101
  - data/EuroSAT
  - data/DTD
  - data/Country211
resize: 
  - null # CIFAR-10 is already 32x32
  - null # CIFAR-100 is already 32x32
  - (32, 32) # MNIST is 28x28
  - null # SVHN is already 32x32
  - (32, 32) # FashionMNIST is 28x28
  - (32, 32) # GTSRB has different sizes
  - null # FaceScrub100 is already 32x32
  - (32, 32) # NotMNIST is 28x28
  - (32, 32) # EMNISTDigits is 28x28
  - (32, 32) # EMNISTLetters is 28x28
  - (32, 32) # ArabicHandwrittenDigits is 28x28
  - (32, 32) # KannadaMNIST is 28x28
  - (32, 32) # SignLanguageMNIST is 28x28
  - (32, 32) # KMNIST is 28x28
  - (32, 32) # Food101 has different sizes
  - null # Linnaeus5_32 is already 32x32
  - (32, 32) # Caltech101 has different sizes
  - (32, 32) # EuroSAT is 64x64
  - (32, 32) # DTD has different sizes
  - (32, 32) # Country211 is 256x256
repeat_channels:
  - null
  - null
  - 3 # MNIST is grayscale
  - null
  - 3 # FashionMNIST is grayscale
  - null
  - null
  - 3 # NotMNIST is grayscale
  - 3 # EMNISTDigits is grayscale
  - 3 # EMNISTLetters is grayscale
  - 3 # ArabicHandwrittenDigits is grayscale
  - 3 # KannadaMNIST is grayscale
  - 3 # SignLanguageMNIST is grayscale
  - 3 # KMNIST is grayscale
  - null
  - null
  - null
  - null
  - null
  - null
custom_transforms:
  - _target_: torchvision.transforms.Compose # For CIFAR-10
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 32
        padding: 4
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
  - _target_: torchvision.transforms.Compose # For CIFAR-100
    transforms:
      - _target_: torchvision.transforms.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.RandomRotation
        degrees: 20
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
      - _target_: torchvision.transforms.RandomAdjustSharpness
        sharpness_factor: 2
        p: 0.2
      - _target_: torchvision.transforms.RandomErasing
        p: 0.75
        scale: [0.02, 0.1]
        value: 1.0
        inplace: False
  - null # For MNIST
  - _target_: torchvision.transforms.Compose # For SVHN
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 32
        padding: 4
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
  - null # For FashionMNIST 
  - _target_: torchvision.transforms.Compose # For GTSRB
    transforms:
      - _target_: torchvision.transforms.RandomAffine
        degrees: 15
        translate: [0.1, 0.1]
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
      - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.Compose # For FaceScrub100
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.RandomRotation
        degrees: 10
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
  - null # For NotMNIST
  - null # For EMNISTDigits
  - null # For EMNISTLetters
  - null # For ArabicHandwrittenDigits
  - null # For KannadaMNIST
  - null # For SignLanguageMNIST
  - null # For KMNIST
  - _target_: torchvision.transforms.Compose # For Food101
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
      - _target_: torchvision.transforms.RandomRotation
        degrees: 10
  - _target_: torchvision.transforms.Compose # For Linnaeus5_32
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.RandomRotation
        degrees: 15
  - _target_: torchvision.transforms.Compose # For Caltech101
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.RandomRotation
        degrees: 15
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
  - _target_: torchvision.transforms.Compose # For EuroSAT
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
      - _target_: torchvision.transforms.RandomRotation
        degrees: 10
  - _target_: torchvision.transforms.Compose # For DTD
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
      - _target_: torchvision.transforms.RandomRotation
        degrees: 15
  - _target_: torchvision.transforms.Compose # For Country211
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
      - _target_: torchvision.transforms.RandomRotation
        degrees: 15