_target_: clarena.cl_datasets.Combined
validation_percentage: 0.1
test_percentage: 0.1
batch_size: 128
datasets: 
  - torchvision.datasets.CIFAR10
  - torchvision.datasets.CIFAR100
  - torchvision.datasets.MNIST
  - torchvision.datasets.SVHN
  - torchvision.datasets.FashionMNIST
  - torchvision.datasets.GTSRB
  - clarena.cl_datasets.original.FaceScrub100
  - clarena.cl_datasets.original.NotMNIST
root: 
  - data/CIFAR10
  - data/CIFAR100
  - data/MNIST
  - data/SVHN
  - data/FashionMNIST
  - data/GTSRB
  - data/FaceScrub100
  - data/NotMNIST
resize: 
  - null # CIFAR-10 is already 32x32
  - null # CIFAR-100 is already 32x32
  - (32, 32) # MNIST is 28x28
  - null # SVHN is already 32x32
  - (32, 32) # FashionMNIST is 28x28
  - (32, 32) # GTSRB has different sizes
  - null # FaceScrub100 is already 32x32
  - (32, 32) # NotMNIST is 28x28
repeat_channels:
  - null
  - null
  - 3 # MNIST is grayscale
  - null
  - 3 # FashionMNIST is grayscale
  - null
  - null
  - 3 # NotMNIST is grayscale
custom_transforms:
  - _target_: torchvision.transforms.Compose # For CIFAR-10
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 32
        padding: 4
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
  - _target_: torchvision.transforms.Compose # For CIFAR-100
    transforms:
      - _target_: torchvision.transforms.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.RandomRotation
        degrees: 20
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
      - _target_: torchvision.transforms.RandomAdjustSharpness
        sharpness_factor: 2
        p: 0.2
      - _target_: torchvision.transforms.RandomErasing
        p: 0.75
        scale: [0.02, 0.1]
        value: 1.0
        inplace: False
  - null # For MNIST
  - _target_: torchvision.transforms.Compose # For SVHN
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 32
        padding: 4
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
  - null # For FashionMNIST 
  - _target_: torchvision.transforms.Compose # For GTSRB
    transforms:
      - _target_: torchvision.transforms.RandomAffine
        degrees: 15
        translate: [0.1, 0.1]
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
      - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.Compose # For FaceScrub100
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.RandomRotation
        degrees: 10
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
  - null # For NotMNIST