_target_: clarena.cl_datasets.PermutedCountry211
root: data/Country211
num_tasks: 20
batch_size: 256
permutation_mode: first_channel_only
resize: (224, 224)
custom_transforms:
  _target_: torchvision.transforms.Compose # For Country211
  transforms:
    - _target_: torchvision.transforms.RandomResizedCrop
      size: 224
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
    - _target_: torchvision.transforms.ToTensor