_target_: clarena.cl_datasets.PermutedOxfordIIITPet
root: data/OxfordIIITPet
target_type: category
num_tasks: 20
validation_percentage: 0.1
batch_size: 128
permutation_mode: first_channel_only
resize: (224, 224)