_target_: clarena.cl_datasets.PermutedFaceScrub
root: data/FaceScrub
size: "100"
num_tasks: 20
validation_percentage: 0.1
batch_size: 64
permutation_mode: first_channel_only
custom_transforms:
  _target_: torchvision.transforms.Compose # For FaceScrub100
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [64, 64]
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.2
      contrast: 0.2
    - _target_: torchvision.transforms.RandomRotation
      degrees: 10