_target_: clarena.cl_datasets.PermutedCIFAR100
root: data/CIFAR100
num_tasks: 20
validation_percentage: 0.1
batch_size: 128
permutation_mode: first_channel_only
custom_transforms:
  _target_: torchvision.transforms.Compose # For CIFAR-100
  transforms:
    - _target_: torchvision.transforms.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomRotation
      degrees: 20
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
    - _target_: torchvision.transforms.RandomAdjustSharpness
      sharpness_factor: 2
      p: 0.2
    - _target_: torchvision.transforms.RandomErasing
      p: 0.75
      scale: [0.02, 0.1]
      value: 1.0
      inplace: False