_target_: clarena.cl_datasets.PermutedCaltech101
root: data/Caltech101
num_tasks: 20
validation_percentage: 0.1
test_percentage: 0.1
batch_size: 256
permutation_mode: first_channel_only
repeat_channels: 3 # this dataset has both RGB and grayscale images, so we need to repeat the channels uniformly to 3
resize: (256, 256)
custom_transforms:
  _target_: torchvision.transforms.Compose # For Caltech101
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [256, 256]
    - _target_: torchvision.transforms.RandomResizedCrop
      size: 224
    - _target_: torchvision.transforms.RandomHorizontalFlip