- _target_: lightning.Trainer
  default_root_dir: ${output_dir}
  log_every_n_steps: 50
  enable_checkpointing: False
  accelerator: mps
  devices: 1
  max_epochs: 2
- _target_: lightning.Trainer
  default_root_dir: ${output_dir}
  log_every_n_steps: 50
  enable_checkpointing: False
  accelerator: mps
  devices: 1
  max_epochs: 20
- _target_: lightning.Trainer
  default_root_dir: ${output_dir}
  log_every_n_steps: 50
  enable_checkpointing: False
  accelerator: mps
  devices: 1
  max_epochs: 20
