_target_: lightning.Trainer

default_root_dir: ${output_dir}

log_every_n_steps: 50

enable_checkpointing: False

accelerator: gpu
devices: 4
strategy: ddp_find_unused_parameters_true

max_epochs: 20

