_target_: clarena.cl_algorithms.HAT
adjustment_mode: adahat
adjustment_intensity: 1e-6
epsilon: 0.1
s_max: 400.0
clamp_threshold: 50.0
mask_sparsity_factor: 0.1
mask_sparsity_mode: original
task_embedding_init: N01