_target_: clarena.callbacks.HATMetricsCallback
test_masks_plot_dir: ./outputs/${output_dir_name}/${now:%Y-%m-%d_%H-%M-%S}/mask/test/
test_cumulative_masks_plot_dir: ./outputs/${output_dir_name}/${now:%Y-%m-%d_%H-%M-%S}/mask/test_cumulative/