_target_: clarena.callbacks.HATMetricsCallback
test_masks_plot_dir: ${output_dir}/mask/test/
test_cumulative_masks_plot_dir: ${output_dir}/mask/test_cumulative/
adjustment_rate_plot_dir: ${output_dir}/adjustment_rate/
plot_adjustment_rate_every_n_steps: 10
