_target_: clarena.cl_algorithms.CBPHAT
adjustment_mode: layer_gradient_x_activation
adjustment_intensity: 1e-6
utility_decay_rate: 1.0
s_max: 400.0
clamp_threshold: 50.0
mask_sparsity_reg_factor: 0.1
mask_sparsity_reg_mode: original
task_embedding_init_mode: N01
epsilon: 0.1
